name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Testing github actions
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.0 

    - name: Build application
      run: go build

    - name: Install SSH client
      run: sudo apt-get update && sudo apt-get install -y openssh-client
    
    - name: See
      run: ls

    - name: Run app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_IP }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd github-repos
          cd password-manager-service
          git pull
          go build
          ./password-manager-service

